project:
  type: website
  output-dir: docs

website:
  title: "Anish Rao"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - href: projects/data-viz/viz_index.qmd
            text: Data Visualization
          - href: projects/taxi-dw/taxi_index.qmd
            text: NYC Taxi Data Warehouse
          - href: projects/churn-prediction/churn_index.qmd
            text: Customer Churn Prediction

format:
  html:
    theme: cosmo
    css: styles.css