project:
  type: website
  output-dir: docs

website:
  title: "Anish Rao"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - href: projects/data-viz/index.qmd
            text: Data Visualization
          - href: projects/taxi-dw/index.qmd
            text: NYC Taxi Data Warehouse

format:
  html:
    theme: cosmo
    css: styles.css